name: Update aqua-checksums.json

on: pull_request

permissions: {}

jobs:
  securefix:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 15
    steps:
      - name: Checkout the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install aqua
        uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
        with:
          aqua_version: v2.53.9

      - name: Fix aqua-checksums.json
        run: aqua upc -prune

      - name: Commit and push
        uses: securefix-action/action@05036cda4e1fcaeba401d23261056048fe20ba27 # v0.2.2
        with:
          app_id: ${{secrets.APP_ID}}
          app_private_key: ${{ secrets.PRIVATE_KEY }}
